"""add rating5

Revision ID: 1ca6a29458a3
Revises: aa4e364a7e60
Create Date: 2024-11-17 20:57:45.958609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca6a29458a3'
down_revision: Union[str, None] = 'aa4e364a7e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_average',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('rating_web', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.drop_column('rating', 'rating_web')
    op.drop_column('rating', 'rating_count')
    op.drop_column('rating', 'rating_average')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.add_column('rating', sa.Column('rating_average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rating', sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rating', sa.Column('rating_web', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    op.create_foreign_key('genre_director_director_name_fkey', 'genre_director', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_unique_constraint('uq_genre_name', 'genre', ['name'])
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.create_foreign_key('director_description_director_id_fkey', 'director_description', 'director', ['director_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('director_description_description_name_fkey', 'director_description', 'description', ['description_name'], ['name'], onupdate='CASCADE')
    op.create_foreign_key('director_description_director_name_fkey', 'director_description', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_unique_constraint('uq_director_name', 'director', ['name'])
    op.create_unique_constraint('uq_description_name', 'description', ['name'])
    op.drop_table('rating_average')
    # ### end Alembic commands ###
