"""Film_connection3

Revision ID: 1d874323e3ef
Revises: 225a2ef261b9
Create Date: 2024-11-03 18:28:30.526186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d874323e3ef'
down_revision: Union[str, None] = '225a2ef261b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('description', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('description', 'name')
    # ### end Alembic commands ###
