"""add user to rating2

Revision ID: 7bf78dc2ad31
Revises: ffafa176b0ff
Create Date: 2024-11-17 13:37:48.044773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf78dc2ad31'
down_revision: Union[str, None] = 'ffafa176b0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('rating_average', sa.Float(), nullable=True))
    op.add_column('rating', sa.Column('rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'rating_count')
    op.drop_column('rating', 'rating_average')
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    op.create_foreign_key('genre_director_director_name_fkey', 'genre_director', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_unique_constraint('uq_genre_name', 'genre', ['name'])
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.create_foreign_key('director_description_director_name_fkey', 'director_description', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_foreign_key('director_description_description_name_fkey', 'director_description', 'description', ['description_name'], ['name'], onupdate='CASCADE')
    op.create_foreign_key('director_description_director_id_fkey', 'director_description', 'director', ['director_id'], ['id'], onupdate='CASCADE')
    op.create_unique_constraint('uq_director_name', 'director', ['name'])
    op.create_unique_constraint('uq_description_name', 'description', ['name'])
    # ### end Alembic commands ###
