"""Films with connections

Revision ID: 97971f26eced
Revises: 0ee7123d2205
Create Date: 2024-11-03 14:50:35.998173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97971f26eced'
down_revision: Union[str, None] = '0ee7123d2205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_description',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['description.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.PrimaryKeyConstraint('director_id', 'description_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_description')
    # ### end Alembic commands ###
