"""add rating3

Revision ID: aa4e364a7e60
Revises: 7bf78dc2ad31
Create Date: 2024-11-17 15:40:51.854448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4e364a7e60'
down_revision: Union[str, None] = '7bf78dc2ad31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.add_column('rating', sa.Column('user_username', sa.String(), nullable=True))
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'user', ['user_username'], ['username'])
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.STRING(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user', ['user_id'], ['id'])
    op.drop_column('rating', 'user_username')
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    op.create_foreign_key('genre_director_director_name_fkey', 'genre_director', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_unique_constraint('uq_genre_name', 'genre', ['name'])
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.drop_constraint(None, 'director_description', type_='foreignkey')
    op.create_foreign_key('director_description_director_id_fkey', 'director_description', 'director', ['director_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('director_description_description_name_fkey', 'director_description', 'description', ['description_name'], ['name'], onupdate='CASCADE')
    op.create_foreign_key('director_description_director_name_fkey', 'director_description', 'director', ['director_name'], ['name'], onupdate='CASCADE')
    op.create_unique_constraint('uq_director_name', 'director', ['name'])
    op.create_unique_constraint('uq_description_name', 'description', ['name'])
    # ### end Alembic commands ###
