"""Database creation

Revision ID: d5d31e50d206
Revises: a518bab7e201
Create Date: 2024-11-15 19:35:52.243888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d31e50d206'
down_revision: Union[str, None] = 'a518bab7e201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_director_name", "director", ["name"])
    op.create_unique_constraint("uq_genre_name", "genre", ["name"])
    op.create_unique_constraint("uq_description_name", "description", ["name"])
    op.add_column('genre_description', sa.Column('director_name', sa.String(), nullable=True))
    op.add_column('genre_description', sa.Column('description_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'genre_description', 'director', ['director_name'], ['name'])
    op.create_foreign_key(None, 'genre_description', 'description', ['description_name'], ['name'])
    op.add_column('genre_director', sa.Column('genre_name', sa.String(), nullable=True))
    op.add_column('genre_director', sa.Column('director_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'genre_director', 'director', ['director_name'], ['name'])
    op.create_foreign_key(None, 'genre_director', 'genre', ['genre_name'], ['name'])
    op.drop_constraint('unique_email', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_director_name", "director", type_="unique")
    op.drop_constraint("uq_genre_name", "genre", type_="unique")
    op.drop_constraint("uq_description_name", "description", type_="unique")
    op.create_unique_constraint('unique_email', 'user', ['email'])
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    op.drop_column('genre_director', 'director_name')
    op.drop_column('genre_director', 'genre_name')
    op.drop_constraint(None, 'genre_description', type_='foreignkey')
    op.drop_constraint(None, 'genre_description', type_='foreignkey')
    op.drop_column('genre_description', 'description_name')
    op.drop_column('genre_description', 'director_name')
    # ### end Alembic commands ###
