"""add

Revision ID: e694e745054d
Revises: d5d31e50d206
Create Date: 2024-11-15 20:07:09.391453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e694e745054d'
down_revision: Union[str, None] = 'd5d31e50d206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'director_description',
        sa.Column('director_id', sa.Integer(), nullable=False),
        sa.Column('description_id', sa.Integer(), nullable=False),
        sa.Column('director_name', sa.String(), nullable=False),
        sa.Column('description_name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['description_id'], ['description.id']),
        sa.ForeignKeyConstraint(['description_name'], ['description.name']),
        sa.ForeignKeyConstraint(['director_id'], ['director.id']),
        sa.ForeignKeyConstraint(['director_name'], ['director.name']),
        sa.PrimaryKeyConstraint('director_id', 'description_id', 'director_name', 'description_name')
    )
    op.drop_table('genre_description')
    
    # Удаление ограничений с использованием SQL с CASCADE
    op.execute("ALTER TABLE description DROP CONSTRAINT uq_description_name CASCADE")
    op.execute("ALTER TABLE director DROP CONSTRAINT uq_director_name CASCADE")
    op.execute("ALTER TABLE genre DROP CONSTRAINT uq_genre_name CASCADE")
    
    op.alter_column(
        'genre_director',
        'genre_name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'genre_director',
        'director_name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    # ### end Alembic commands ###
