"""add user to rating

Revision ID: ffafa176b0ff
Revises: 1859ac218097
Create Date: 2024-11-17 13:30:36.772578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffafa176b0ff'
down_revision: Union[str, None] = '1859ac218097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'user_id')
    op.drop_constraint(None, 'genre_director', type_='foreignkey')
    # ### end Alembic commands ###
